INPUT_MODE = 'auto'  # 'console' / 'auto'

STEP_RATE = 1/240.  # one spep lenght in seconds
DURATION = 900     # steps of simulation with given STEP_RATE

COCHONNET_RADIUS = 0.2
BALL_RADIUS = 0.4

BALL_MASS = 0.33
BALL_BOUNCENES = 0.8

PLANE_BOUNCENESS = 0.65
PLANE_LAT_FRIC = 0.6
PLANE_ROL_FRIC = 0

POWER = 200
START_POSITION = (0, 0, 1)

BALLS_IN_ROUND = 2
ROUNDS_IN_GAME = 3
